'use strict';
/* CONFIRM POPUP ****************88
var isconfirmed = confirm("are you sure nigga?")
if(isconfirmed == true) {
    document.write("Thanks!! you images are deleted successfully")
} else {
    document.write("Thanks!! your images are not deleted")
} */
/* PROMPT POPUP ***********
var res = prompt("enter your race?");
console.log("race", res);
document.write("your race is " + res); */
document.getElementById("para").innerHTML = "hello guys i am the new paragraph"
document.getElementById("divi").innerHTML = "hello guys i am the new division";
