'use strict';
/* FOR LOOP ******************
const i = 10;
for (let i = 0; i < 10; i++) {
    console.log("number" + i);  
} */
/* WHILE LOOP **************
var i = 0;
while (i<10) {
    console.log("number is " + i);
    i ++;
}
 */
/* DO WHILE ***************
var i = 0;
do {
    console.log("number is " + i);
    i++;
} while(i<10);
 */
/* FOR IN LOOP *****************
var student = {
    name : "karthik",
    age : 24 ,
    hobby : "gym",
}
for(var data in student){
    console.log(student[data]);
} */
/* FOR OF *****************
var arr = [10 , 20 , 30, 40 , 50];
for(var data in arr){
    console.log(arr[[data]]);
}
 */