'USE STRICT';
//
/* var person = {
    name: "karthik",
    age: 24,
    height: 5.11,
    gender: "male",
    qualification: "btech",
    dance: function() {
        console.log("i am karthik")
    }
}
    var keys = Object.keys(person);
    console.log(keys);
    var keys = Object.values(person);
    console.log(keys);
/*var person = new Object();
person.name = "karthik";
person.age = 24;
person.gender = "male";  
dance = function() {
    console.log("karthik is a good boy");
}

dance();*/
/*var male = "Karthik gym";
console.log(typeof male);
console.log(male); */
//var female = new String("karthik");
//console.log(typeof female);
//console.log(male + "" + female);
//console.log(male.length);
//console.log(male===female);
//console.log(male.charAt(5));
/*console.log(male.replace("gym","bike"));
console.log(male.trim()+ 'karthik'); */
var str  = "karthik janapatla"
console.log(str.substr(4,5));



